### ISSUE TITLE
Bitbucket project not found

### ISSUE THREAD

**Issue by durf1** [afklm/atlasman#33] opened 2016-06-28 10:23 UTC
Here a example of a project existing in bitbucket but not found by atlasman

https://stash.eden.klm.com/projects/TCSURCCROM

Tip: no repository exist with this name.

**Comment by bv1p** [comment] 2016-06-28 10:33
Currently the "repository" search only searches for repositories :).

**Comment by mvdkleijn** [comment] 2016-07-13 13:39
Closing this as its not a bug.

**Closed** 2016-07-13 13:40 UTC
Labels: bug, invalid, ready
